lecture18.zip: popcorn3.html popcorn3.php index.html examples.txt
	mkdir lecture18
	cp popcorn3.* index.html examples.txt lecture18
	zip -r lecture18.zip lecture18
	rm -rf lecture18

all: lecture18.zip


